# Generated by Django 5.0.6 on 2024-05-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='response',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='user_input',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
